name: sccellfie
owner: iuc
description: "Metabolic activity from single-cell and spatial transcriptomics with scCellFie"
homepage_url: https://sccellfie.readthedocs.io/en/latest/
long_description: |
    scCellFie is a Python-based tool for analyzing metabolic activity at different resolutions, developed at the Vento Lab. It efficiently processes both single-cell and spatial data to predict metabolic task activities. While its prediction strategy is inspired by CellFie, a tool from the Lewis Lab originally developed in MATLAB for bulk and small single-cell datasets, scCellFie includes a series of improvements and new analyses, such as marker selection, differential analysis, and cell-cell communication inference.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/sccellfie/
type: unrestricted
categories:
  - Single Cell
  - Spatial Omics
  - Transcriptomics
  - Metabolomics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the sccellfie tool suite: {{ tool_name }}"
suite:
  name: "suite_sccellfie"
  description: "scCellFie – Metabolic Activity Analysis in Python"
  long_description: |
    scCellFie is a scalable toolkit for analyzing metabolic activity from single-cell and spatial transcriptomicss data. It includes preprocessing, visualization, clustering, pseudotime and trajectory inference and differential expression testing.